"use client";
import { useEffect, useState } from "react";
import AdminShell from "../../../components/AdminShell";
import { supabase } from "../../../lib/supabase";

type Tx={id:string;transaction_at:string;employee_name:string;employee_identifier:string;department:string|null;product_name:string;variant_name:string;quantity:number;total_volume_litres:number;total_amount:number};

export default function MonthlyReport(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[rows,setRows]=useState<Tx[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{setLoading(true);const s=new Date(month+"-01T00:00:00"),e=new Date(s);e.setMonth(e.getMonth()+1);supabase.from("transaction_report").select("id,transaction_at,employee_name,employee_identifier,department,product_name,variant_name,quantity,total_volume_litres,total_amount").gte("transaction_at",s.toISOString()).lt("transaction_at",e.toISOString()).order("transaction_at",{ascending:false}).then(({data,error:x})=>{setError(x?.message||"");setRows((data??[])as Tx[]);setLoading(false)})},[month]);
 const exportXlsx=async()=>{const XLSX=await import("xlsx");const data=rows.map(r=>({"Date & Time":new Date(r.transaction_at).toLocaleString(),"Employee Name":r.employee_name,"Employee ID":r.employee_identifier,"Department":r.department??"","Product":r.product_name,"Variant":r.variant_name,"Qty":r.quantity,"Volume (L)":Number(r.total_volume_litres),"Amount (₹)":Number(r.total_amount)}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Monthly Report");XLSX.writeFile(wb,`monthly-report-${month}.xlsx`)};
 const qty=rows.reduce((s,r)=>s+r.quantity,0),litres=rows.reduce((s,r)=>s+Number(r.total_volume_litres),0),value=rows.reduce((s,r)=>s+Number(r.total_amount),0),people=new Set(rows.map(r=>r.employee_identifier)).size;
 return <AdminShell><div className="main"><header className="topbar"><div><h1>Monthly Report</h1><p>Detailed activity and monthly totals.</p></div><div className="report-controls"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button className="primary-button small-button" onClick={exportXlsx} disabled={!rows.length}>Export Excel</button></div></header><section className="stats"><article className="stat"><div className="stat-label">Employees Served</div><div className="stat-value">{people}</div></article><article className="stat"><div className="stat-label">Packets / Units</div><div className="stat-value">{qty}</div></article><article className="stat"><div className="stat-label">Volume</div><div className="stat-value">{litres.toFixed(2)} L</div></article><article className="stat"><div className="stat-label">Value</div><div className="stat-value">₹{value.toFixed(2)}</div></article></section>{error&&<p className="error-text">{error}</p>}<section className="panel table-panel"><table><thead><tr><th>Date & time</th><th>Employee</th><th>ID</th><th>Department</th><th>Product</th><th>Variant</th><th>Qty</th><th>Volume</th><th>Amount</th></tr></thead><tbody>{loading?<tr><td colSpan={9}>Loading...</td></tr>:rows.length===0?<tr><td colSpan={9}>No transactions for this month.</td></tr>:rows.map(r=><tr key={r.id}><td>{new Date(r.transaction_at).toLocaleString()}</td><td><strong>{r.employee_name}</strong></td><td>{r.employee_identifier}</td><td>{r.department||"—"}</td><td>{r.product_name}</td><td>{r.variant_name}</td><td>{r.quantity}</td><td>{Number(r.total_volume_litres).toFixed(3)} L</td><td>₹{Number(r.total_amount).toFixed(2)}</td></tr>)}</tbody></table></section></div></AdminShell>
}