"use client";
import{useEffect,useState}from"react";import Link from"next/link";import{supabase}from"../../../lib/supabase";
type Tx={id:string;transaction_at:string;employee_name:string;employee_identifier:string;department:string|null;product_name:string;variant_name:string;quantity:number;total_volume_litres:number;total_amount:number};
const nav=[["/dashboard","Dashboard"],["/employees","Employees"],["/products","Products & Prices"],["/transactions","Transactions"],["/reports/daily","Daily Report"],["/reports/monthly","Monthly Report"]];
export default function MonthlyReport(){const[month,setMonth]=useState(new Date().toISOString().slice(0,7));const[rows,setRows]=useState<Tx[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
useEffect(()=>{setLoading(true);const s=new Date(month+"-01T00:00:00"),e=new Date(s);e.setMonth(e.getMonth()+1);supabase.from("transaction_report").select("id,transaction_at,employee_name,employee_identifier,department,product_name,variant_name,quantity,total_volume_litres,total_amount").gte("transaction_at",s.toISOString()).lt("transaction_at",e.toISOString()).order("transaction_at",{ascending:false}).then(({data,error:x})=>{setError(x?.message||"");setRows((data??[])as Tx[]);setLoading(false)})},[month]);
const csv=()=>{const h=["Date","Employee Name","Employee ID","Department","Product","Variant","Qty","Litres","Amount"],b=rows.map(r=>[new Date(r.transaction_at).toLocaleString(),r.employee_name,r.employee_identifier,r.department??"",r.product_name,r.variant_name,r.quantity,Number(r.total_volume_litres).toFixed(3),Number(r.total_amount).toFixed(2)]);const t=[h,...b].map(x=>x.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type:"text/csv"}));a.download=`monthly-report-${month}.csv`;a.click()};
const qty=rows.reduce((s,r)=>s+r.quantity,0),litres=rows.reduce((s,r)=>s+Number(r.total_volume_litres),0),value=rows.reduce((s,r)=>s+Number(r.total_amount),0),people=new Set(rows.map(r=>r.employee_identifier)).size;
return <Shell active="/reports/monthly"><header className="topbar"><div><h1>Monthly Report</h1><p>Detailed activity and monthly totals.</p></div><div className="report-controls"><input type="month"value={month}onChange={e=>setMonth(e.target.value)}/><button className="primary-button small-button"onClick={csv}disabled={!rows.length}>Export CSV</button></div></header><section className="stats"><article className="stat"><div className="stat-label">Employees Served</div><div className="stat-value">{people}</div></article><article className="stat"><div className="stat-label">Packets / Units</div><div className="stat-value">{qty}</div></article><article className="stat"><div className="stat-label">Volume</div><div className="stat-value">{litres.toFixed(2)} L</div></article><article className="stat"><div className="stat-label">Value</div><div className="stat-value">₹{value.toFixed(2)}</div></article></section>{error&&<p className="error-text">{error}</p>}<section className="panel table-panel"><table><thead><tr><th>Date & time</th><th>Employee</th><th>ID</th><th>Department</th><th>Product</th><th>Variant</th><th>Qty</th><th>Volume</th><th>Amount</th></tr></thead><tbody>{loading?<tr><td colSpan={9}>Loading...</td></tr>:rows.length===0?<tr><td colSpan={9}>No transactions for this month.</td></tr>:rows.map(r=><tr key={r.id}><td>{new Date(r.transaction_at).toLocaleString()}</td><td><strong>{r.employee_name}</strong></td><td>{r.employee_identifier}</td><td>{r.department||"—"}</td><td>{r.product_name}</td><td>{r.variant_name}</td><td>{r.quantity}</td><td>{Number(r.total_volume_litres).toFixed(3)} L</td><td>₹{Number(r.total_amount).toFixed(2)}</td></tr>)}</tbody></table></section></Shell>}
function Shell({children,active}:{children:React.ReactNode;active:string}){return <div className="admin-shell"><aside className="sidebar"><div className="sidebar-brand">Honest Milk · Admin</div><nav className="nav">{nav.map(([href,label])=><Link className={`nav-item ${active===href?"active":""}`}href={href}key={href}>{label}</Link>)}</nav></aside><main className="main">{children}</main></div>}